# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
CONFIG_ZMK_IDLE_TIMEOUT=3600000

# Uncomment these two lines to add support for encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_ZMK_KEYBOARD_NAME="Sofle" 

# 增加键盘的 BLE 无线电的发射功率，用解决延迟和左右通讯不佳的问题
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

CONFIG_ZMK_DISPLAY=y

# Habilita el widget que muestra el estado de las capas
CONFIG_ZMK_WIDGET_LAYER_STATUS=y

# Habilita el widget que muestra el estado de la batería
# Nota: Esto es más útil en teclados inalámbricos.
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y

# Habilita el widget que muestra el estado de la conexión (USB o Bluetooth)
# CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y

# Habilita el widget que muestra los modificadores (Caps Lock, Num Lock, etc.)
# CONFIG_ZMK_WIDGET_MODS_STATUS=y
